### ISSUE TITLE
Scripts to reproduce experiments; Exceptions for running baseline PredCls on VG

### ISSUE THREAD

**Issue by j-rausch** [ubc-vision/segmentation-sg#11]
Hey!

I'd like to reproduce the experiments and am running into some more exceptions at the moment.

After fixing the [compatibility issues](https://github.com/ubc-vision/segmentation-sg/issues/8) in sg_trainer.py, I'm trying to run a simple baseline experiment (PredCls on Visual Genome, no segmentation, no COCO).

Since I couldn't find configs for this, I created a new config file and training script.
To reproduce the error, I added them in a branch here: [config](https://github.com/j-rausch/segmentation-sg/blob/baseline_experiments/configs/precls_vg.yaml) and [training script](https://github.com/j-rausch/segmentation-sg/blob/baseline_experiments/scripts/train_predcls.py)

The command options were:
```python train_predcls.py --config-file ../configs/precls_vg.yaml --num-gpus 4 --resume DATASETS.VISUAL_GENOME.IMAGES ../datasets/vg/VG_100K/ DATASETS.VISUAL_GENOME.MAPPING_DICTIONARY ../datasets/vg/VG-SGG-dicts-with-attri.json DATASETS.VISUAL_GENOME.IMAGE_DATA ../datasets/vg/image_data.json DATASETS.VISUAL_GENOME.VG_ATTRIBUTE_H5 ../datasets/vg/VG-SGG-with-attri.h5 OUTPUT_DIR ../data/debug/predcls_baseline/```

When running this script, I'm running into this error:
```
[01/30 12:46:55 d2.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
[01/30 12:46:55 d2.utils.events]:  iter: 1  total_loss: 0.4324  loss_rel: 0.4324  loss_refine_obj: 0  data_time: 25.7758  lr: 0.001  max_mem: 8603M
Traceback (most recent call last):
  File "/pathto/git/segmentationsg/scripts/train_predcls.py", line 69, in <module>
    launch(
  File "/pathto/anaconda3/envs/sgg_torch16_detectron03_segmentationsg/lib/python3.8/site-packages/detectron2/engine/launch.py", line 55, in launch
    mp.spawn(
  File "/pathto/anaconda3/envs/sgg_torch16_detectron03_segmentationsg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/pathto/anaconda3/envs/sgg_torch16_detectron03_segmentationsg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/pathto/anaconda3/envs/sgg_torch16_detectron03_segmentationsg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/pathto/anaconda3/envs/sgg_torch16_detectron03_segmentationsg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/pathto/anaconda3/envs/sgg_torch16_detectron03_segmentationsg/lib/python3.8/site-packages/detectron2/engine/launch.py", line 94, in _distributed_worker
    main_func(*args)
  File "/pathto/git/segmentationsg/scripts/train_predcls.py", line 51, in main
    return trainer.train()
  File "/pathto/anaconda3/envs/sgg_torch16_detectron03_segmentationsg/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 413, in train
    super().train(self.start_iter, self.max_iter)
  File "/pathto/anaconda3/envs/sgg_torch16_detectron03_segmentationsg/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 134, in train
    self.run_step()
  File "/pathto/anaconda3/envs/sgg_torch16_detectron03_segmentationsg/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 423, in run_step
    self._trainer.run_step()
  File "/pathto/anaconda3/envs/sgg_torch16_detectron03_segmentationsg/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 228, in run_step
    loss_dict = self.model(data)
  File "/pathto/anaconda3/envs/sgg_torch16_detectron03_segmentationsg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/pathto/anaconda3/envs/sgg_torch16_detectron03_segmentationsg/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 528, in forward
    self.reducer.prepare_for_backward([])
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).

Process finished with exit code 1
```
(full log is attached)
[error_log.txt](https://github.com/ubc-vision/segmentation-sg/files/7965849/error_log.txt)

I think `find_unused_parameters=True` could only be added by modifying the `launch()` code, but the default one from  the detectron2.engine.launch is used in the import statements. Perhaps I chose some wrong options, or is this expected and accounted for in the modified detectron2 installation you mentioned te be using before?

Could you possibly share the configs/scripts that allow reproducing the other experiments in the paper, including the baselines?

**Comment by siddheshk** [comment]
The error is because of some parameters not being used in the baseline model. That is expected as the default framework has segmentation modules attached. I don't have the pretrained model weights trained on Visual Genome without using joint training with MSCOCO. So you might have to do that portion of the training. But I've added two config files and two scripts: one for pretraining the baseline object detector and the other for training the baseline scenegraph model. You can find them [here](https://github.com/ubc-vision/segmentation-sg/tree/main/configs) and [here](https://github.com/ubc-vision/segmentation-sg/tree/main/scripts).
