### ISSUE TITLE
Detector pretraining crashes in first loop due to unexpected prediction tensor shape

### ISSUE THREAD

**Issue by j-rausch** [ubc-vision/segmentation-sg#5]
Thanks again for the great repo!

I'm currently trying to reproduce the baseline/segmentation-grounded results for MOTIF.

After making some adjustments that I describe [here](https://github.com/ubc-vision/segmentation-sg/issues/4), the training loop starts to execute.

In the first iteration, following exception occurs:
```
Traceback (most recent call last):
  File "/pathtoenv/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/pathto/segmentationsg/engine/trainer.py", line 302, in run_step
    loss_dict = self.model(data, mask_batched_inputs=mask_data)
  File "/pathtoenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/pathtoenv/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/pathtoenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/pathto/segmentationsg/modeling/meta_arch/rcnn.py", line 405, in forward
    _, mask_detector_losses = self.roi_heads(mask_images, mask_features, mask_proposals, mask_gt_instances, is_transfer=False)
  File "/pathtoenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/pathto/segmentationsg/modeling/roi_heads/roi_heads.py", line 930, in forward
    losses = self._forward_box(features, proposals, is_transfer=is_transfer)
  File "/pathto/segmentationsg/modeling/roi_heads/roi_heads.py", line 967, in _forward_box
    losses = self.box_predictor.losses(predictions, proposals)
  File "/pathtoenv/lib/python3.8/site-packages/detectron2/modeling/roi_heads/fast_rcnn.py", line 323, in losses
    "loss_box_reg": self.box_reg_loss(
  File "/pathtoenv/lib/python3.8/site-packages/detectron2/modeling/roi_heads/fast_rcnn.py", line 342, in box_reg_loss
    fg_pred_deltas = pred_deltas.view(-1, self.num_classes, box_dim)[
RuntimeError: shape '[-1, 150, 4]' is invalid for input of size 327680
```

The `pred_deltas` tensor seems to normally be of the shape `(1024, 600)` for the images in a batch, which gets reshaped to `(40,4)`.
In the next batch, the `predictions` tuple contains tensors with the shapes of `(1024, 81)` and `(1024, 320)`, which leads to the error. 

I assume this has to do with the different number of classes in COCO and VG? Is there perhaps some config/adjustment/pretrainign that I'm missing?

**Comment by siddheshk** [comment]
Can you tell me the exact command you are running? It will help me understand the error better. Thanks.

**Comment by j-rausch** [comment]
Hey, this specific issue seems not to occur after the codebase update and switching to detectron2
